In [908]:
import pandas as pd
df = pd.read_csv("dataset_pandas_mt.csv")
df.head()

,Customer_ID,Name,Age,Gender,City,Product,Price,Quantity,Payment_Mode,Purchase_Date
0,1,Chetan,NaN,Male,Chennai,Laptop,45042,3,UPI,2023-07-08
1,2,Bala,NaN,Female,Hyderabad,Tablet,16621,5,Cash,2023-12-20
2,3,Jaya,NaN,Female,Hyderabad,Laptop,30794,1,Card,2023-07-04
3,4,Hari,NaN,Male,Hyderabad,Laptop,49912,2,Cash,2023-06-29
4,5,Isha,45.0,Male,Kochi,Tablet,20258,2,Cash,2023-10-08

In [909]:
df.shape

(1050, 10)

In [910]:
df.columns

Index(['Customer_ID', 'Name', 'Age', 'Gender', 'City', 'Product', 'Price',
       'Quantity', 'Payment_Mode', 'Purchase_Date'],
      dtype='str')

In [911]:
df.dtypes

Customer_ID        int64
Name                 str
Age              float64
Gender               str
City                 str
Product              str
Price              int64
Quantity           int64
Payment_Mode         str
Purchase_Date        str
dtype: object

In [912]:
df.isnull().sum()

Customer_ID        0
Name               0
Age              547
Gender             0
City               0
Product            0
Price              0
Quantity           0
Payment_Mode       0
Purchase_Date      0
dtype: int64

In [913]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    1050 non-null   int64
 1   Name           1050 non-null   str
 2   Age            503 non-null    float64
 3   Gender         1050 non-null   str
 4   City           1050 non-null   str
 5   Product        1050 non-null   str
 6   Price          1050 non-null   int64
 7   Quantity       1050 non-null   int64
 8   Payment_Mode   1050 non-null   str
 9   Purchase_Date  1050 non-null   str
dtypes: float64(1), int64(3), str(6)
memory usage: 82.2 KB

In [914]:
df.isnull().sum()

Customer_ID        0
Name               0
Age              547
Gender             0
City               0
Product            0
Price              0
Quantity           0
Payment_Mode       0
Purchase_Date      0
dtype: int64

In [915]:
df["Age"].isnull().sum()

np.int64(547)

In [916]:
print(df.columns)

Index(['Customer_ID', 'Name', 'Age', 'Gender', 'City', 'Product', 'Price',
       'Quantity', 'Payment_Mode', 'Purchase_Date'],
      dtype='str')

In [917]:
print(df.head())

   Customer_ID    Name   Age  Gender       City Product  Price  Quantity  \
0            1  Chetan   NaN    Male    Chennai  Laptop  45042         3
1            2    Bala   NaN  Female  Hyderabad  Tablet  16621         5
2            3    Jaya   NaN  Female  Hyderabad  Laptop  30794         1
3            4    Hari   NaN    Male  Hyderabad  Laptop  49912         2
4            5    Isha  45.0    Male      Kochi  Tablet  20258         2

  Payment_Mode Purchase_Date
0          UPI    2023-07-08
1         Cash    2023-12-20
2         Card    2023-07-04
3         Cash    2023-06-29
4         Cash    2023-10-08

In [918]:
print(df.shape)

(1050, 10)

In [919]:
df["Age"].median()

np.float64(39.0)

In [920]:
df["Age"] = df["Age"].fillna(df["Age"]).median()
print(df["Age"])

0       39.0
1       39.0
2       39.0
3       39.0
4       39.0
        ...
1045    39.0
1046    39.0
1047    39.0
1048    39.0
1049    39.0
Name: Age, Length: 1050, dtype: float64

In [921]:

print(f"Sum of Missing values in Age :{df["Age"].isnull().sum()} ")

Sum of Missing values in Age :0

In [922]:
df["Age"].head(10)

0    39.0
1    39.0
2    39.0
3    39.0
4    39.0
5    39.0
6    39.0
7    39.0
8    39.0
9    39.0
Name: Age, dtype: float64

In [923]:
print(f"Before removing duplicates : {df.shape[0]}")
print(f"duplicated records:{df.duplicated().sum()}")
dp = df.duplicated().sum()
print(f"Duplicated_entries : {dp}")

Before removing duplicates : 1050
duplicated records:50
Duplicated_entries : 50

In [924]:
print(f"After removing duplicates : {   df.drop_duplicates()} ")
after_dropping_duplicates = df.drop_duplicates()
print(f"After removing duplicates checking the number of rows : {after_dropping_duplicates.shape[0]}")

After removing duplicates :      Customer_ID    Name   Age  Gender       City     Product  Price  \
0              1  Chetan  39.0    Male    Chennai      Laptop  45042
1              2    Bala  39.0  Female  Hyderabad      Tablet  16621
2              3    Jaya  39.0  Female  Hyderabad      Laptop  30794
3              4    Hari  39.0    Male  Hyderabad      Laptop  49912
4              5    Isha  39.0    Male      Kochi      Tablet  20258
..           ...     ...   ...     ...        ...         ...    ...
995          996  Chetan  39.0  Female  Hyderabad      Tablet  29084
996          997  Farhan  39.0    Male    Chennai      Mobile  18051
997          998  Chetan  39.0  Female    Chennai  Headphones  39070
998          999    Arun  39.0  Female  Hyderabad      Camera   8705
999         1000    Bala  39.0    Male  Hyderabad      Laptop  41259

     Quantity Payment_Mode Purchase_Date
0           3          UPI    2023-07-08
1           5         Cash    2023-12-20
2           1         Card    2023-07-04
3           2         Cash    2023-06-29
4           2         Cash    2023-10-08
..        ...          ...           ...
995         5         Cash    2023-06-13
996         4         Card    2023-06-06
997         3         Card    2023-03-03
998         3         Cash    2023-06-27
999         2         Card    2023-08-05

[1000 rows x 10 columns]
After removing duplicates checking the number of rows : 1000

In [925]:
sum_of_duplicated = after_dropping_duplicates.duplicated().sum()
print(f"Sum of duplicated : {sum_of_duplicated}")

Sum of duplicated : 0

In [926]:
converting_to_datetime = df["Purchase_Date"].dtype
print(f"Coverting to datetime : {converting_to_datetime}")

Coverting to datetime : str

In [927]:
print(df["Purchase_Date"])
df["Purchase_Date"] = pd.to_datetime(df["Purchase_Date"])
print(f" Datatype_of_purchase_date : {df["Purchase_Date"].dtype}")

0       2023-07-08
1       2023-12-20
2       2023-07-04
3       2023-06-29
4       2023-10-08
           ...
1045    2023-10-18
1046    2023-11-14
1047    2023-12-22
1048    2023-11-26
1049    2023-01-10
Name: Purchase_Date, Length: 1050, dtype: str
 Datatype_of_purchase_date : datetime64[us]

In [928]:
renaming_payment_mode = df.rename(columns={"Payment_Mode" : "PaymentType"})
print(renaming_payment_mode)

      Customer_ID    Name   Age  Gender        City     Product  Price  \
0               1  Chetan  39.0    Male     Chennai      Laptop  45042
1               2    Bala  39.0  Female   Hyderabad      Tablet  16621
2               3    Jaya  39.0  Female   Hyderabad      Laptop  30794
3               4    Hari  39.0    Male   Hyderabad      Laptop  49912
4               5    Isha  39.0    Male       Kochi      Tablet  20258
...           ...     ...   ...     ...         ...         ...    ...
1045          300    Gopi  39.0    Male     Chennai      Mobile  14710
1046          833    Esha  39.0    Male  Trivandrum      Mobile  17436
1047          176    Arun  39.0    Male       Kochi      Tablet  19076
1048          897    Isha  39.0    Male  Trivandrum  Headphones   2578
1049          600  Chetan  39.0    Male  Trivandrum  Headphones  35903

      Quantity PaymentType Purchase_Date
0            3         UPI    2023-07-08
1            5        Cash    2023-12-20
2            1        Card    2023-07-04
3            2        Cash    2023-06-29
4            2        Cash    2023-10-08
...        ...         ...           ...
1045         3        Card    2023-10-18
1046         3         UPI    2023-11-14
1047         5        Card    2023-12-22
1048         4        Card    2023-11-26
1049         1        Card    2023-01-10

[1050 rows x 10 columns]

In [929]:
df["Total_amount"] = df["Price"] * df["Quantity"]
print(df[["Price", "Quantity", "Total_amount"]].head())

   Price  Quantity  Total_amount
0  45042         3        135126
1  16621         5         83105
2  30794         1         30794
3  49912         2         99824
4  20258         2         40516

In [930]:
df["Age_Group"] = pd.cut(
    df["Age"],
    bins = [0, 25, 35, 50, float("inf")],
    labels=["18-25", "26-35", "36-50", "51+"]

)

In [931]:
print(df[["Age", "Age_Group"]].head(20))

     Age Age_Group
0   39.0     36-50
1   39.0     36-50
2   39.0     36-50
3   39.0     36-50
4   39.0     36-50
5   39.0     36-50
6   39.0     36-50
7   39.0     36-50
8   39.0     36-50
9   39.0     36-50
10  39.0     36-50
11  39.0     36-50
12  39.0     36-50
13  39.0     36-50
14  39.0     36-50
15  39.0     36-50
16  39.0     36-50
17  39.0     36-50
18  39.0     36-50
19  39.0     36-50

In [932]:
print(df.dtypes)

Customer_ID               int64
Name                        str
Age                     float64
Gender                      str
City                        str
Product                     str
Price                     int64
Quantity                  int64
Payment_Mode                str
Purchase_Date    datetime64[us]
Total_amount              int64
Age_Group              category
dtype: object

In [933]:
df["Customer_ID"] = df["Customer_ID"].astype("int32")
df["Age"] = df["Age"].astype("int8")
df["Quantity"] = df["Quantity"].astype("int8")
df["Price"] = df["Price"].astype("int32")

In [934]:
df["Total_amount"] = df["Total_amount"].astype("int32")

In [935]:
df["Gender"] = df["Gender"].astype("category")
df["City"] = df["City"].astype("category")
df["Product"] = df["Product"].astype("category")
if "PaymentType" in df.columns:
    df["PaymentType"] = df["PaymentType"].astype("category")
elif "Payment_Mode" in df.columns:
    df["Payment_Mode"] = df["Payment_Mode"].astype("category")
else:
    raise KeyError("Neither 'PaymentType' nor 'Payment_Mode' exists in df.")
df["Age_Group"] = df["Age_Group"].astype("category")

In [936]:
print(df[[
    "Price",
    "Quantity",
    "Total_amount",
    "Age",
    "Age_Group"

]].head(10))

print(df.dtypes)

   Price  Quantity  Total_amount  Age Age_Group
0  45042         3        135126   39     36-50
1  16621         5         83105   39     36-50
2  30794         1         30794   39     36-50
3  49912         2         99824   39     36-50
4  20258         2         40516   39     36-50
5  25157         1         25157   39     36-50
6  18287         1         18287   39     36-50
7  49675         5        248375   39     36-50
8   5485         3         16455   39     36-50
9  25442         4        101768   39     36-50
Customer_ID               int32
Name                        str
Age                        int8
Gender                 category
City                   category
Product                category
Price                     int32
Quantity                   int8
Payment_Mode           category
Purchase_Date    datetime64[us]
Total_amount              int32
Age_Group              category
dtype: object

In [937]:
print(df.columns)

Index(['Customer_ID', 'Name', 'Age', 'Gender', 'City', 'Product', 'Price',
       'Quantity', 'Payment_Mode', 'Purchase_Date', 'Total_amount',
       'Age_Group'],
      dtype='str')

In [938]:
kochi_data = df[df["City"] == "Kochi"]
print(kochi_data)

      Customer_ID    Name  Age  Gender   City     Product  Price  Quantity  \
4               5    Isha   39    Male  Kochi      Tablet  20258         2
5               6  Farhan   39    Male  Kochi      Camera  25157         1
12             13    Arun   39  Female  Kochi  Headphones  23958         5
14             15    Bala   39    Male  Kochi      Camera  42843         1
19             20  Farhan   39    Male  Kochi  Headphones  41910         1
...           ...     ...  ...     ...    ...         ...    ...       ...
1025          308   Divya   39    Male  Kochi      Laptop  16900         5
1033          712  Chetan   39    Male  Kochi      Laptop  14348         4
1043           57    Gopi   39    Male  Kochi      Camera  24035         2
1044          826    Gopi   39    Male  Kochi  Headphones  10261         1
1047          176    Arun   39    Male  Kochi      Tablet  19076         5

     Payment_Mode Purchase_Date  Total_amount Age_Group
4            Cash    2023-10-08         40516     36-50
5            Cash    2023-01-09         25157     36-50
12           Cash    2023-04-07        119790     36-50
14           Card    2023-11-13         42843     36-50
19            UPI    2023-11-25         41910     36-50
...           ...           ...           ...       ...
1025         Card    2023-10-28         84500     36-50
1033         Cash    2023-09-13         57392     36-50
1043         Card    2023-11-20         48070     36-50
1044          UPI    2023-12-28         10261     36-50
1047         Card    2023-12-22         95380     36-50

[211 rows x 12 columns]

In [939]:
print(df[df["City"] == "Kochi"]
      [[
    "Customer_ID",
    "City",
    "Product",
    "Price",
    "Quantity",
    "Total_amount"
]].head())

    Customer_ID   City     Product  Price  Quantity  Total_amount
4             5  Kochi      Tablet  20258         2         40516
5             6  Kochi      Camera  25157         1         25157
12           13  Kochi  Headphones  23958         5        119790
14           15  Kochi      Camera  42843         1         42843
19           20  Kochi  Headphones  41910         1         41910

In [940]:
high_value = df[df["Total_amount"] > 100000]  
print(high_value.head())

    Customer_ID    Name  Age  Gender       City     Product  Price  Quantity  \
0             1  Chetan   39    Male    Chennai      Laptop  45042         3
7             8    Isha   39  Female  Bangalore      Laptop  49675         5
9            10  Chetan   39    Male  Bangalore      Camera  25442         4
12           13    Arun   39  Female      Kochi  Headphones  23958         5
16           17    Jaya   39  Female  Bangalore      Mobile  44114         3

   Payment_Mode Purchase_Date  Total_amount Age_Group
0           UPI    2023-07-08        135126     36-50
7           UPI    2023-05-25        248375     36-50
9          Card    2023-12-24        101768     36-50
12         Cash    2023-04-07        119790     36-50
16          UPI    2023-02-20        132342     36-50

In [941]:
print(df[df["Total_amount"] > 100000][[
    "Customer_ID",
    "Product",
    "Price",
    "Quantity",
    "Total_amount"
]])

      Customer_ID     Product  Price  Quantity  Total_amount
0               1      Laptop  45042         3        135126
7               8      Laptop  49675         5        248375
9              10      Camera  25442         4        101768
12             13  Headphones  23958         5        119790
16             17      Mobile  44114         3        132342
...           ...         ...    ...       ...           ...
1028          741      Laptop  48115         4        192460
1029          384      Mobile  48035         4        192140
1037          816      Camera  39837         3        119511
1038          343      Camera  23661         5        118305
1042          134      Tablet  31493         4        125972

[305 rows x 5 columns]

In [942]:
kochi_data = df.query("City == 'Kochi'")
print(kochi_data.head())

    Customer_ID    Name  Age  Gender   City     Product  Price  Quantity  \
4             5    Isha   39    Male  Kochi      Tablet  20258         2
5             6  Farhan   39    Male  Kochi      Camera  25157         1
12           13    Arun   39  Female  Kochi  Headphones  23958         5
14           15    Bala   39    Male  Kochi      Camera  42843         1
19           20  Farhan   39    Male  Kochi  Headphones  41910         1

   Payment_Mode Purchase_Date  Total_amount Age_Group
4          Cash    2023-10-08         40516     36-50
5          Cash    2023-01-09         25157     36-50
12         Cash    2023-04-07        119790     36-50
14         Card    2023-11-13         42843     36-50
19          UPI    2023-11-25         41910     36-50

In [943]:
age_data = df.query("Age > 40")
print(age_data)

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, City, Product, Price, Quantity, Payment_Mode, Purchase_Date, Total_amount, Age_Group]
Index: []

In [944]:
laptop_data = df.query("Product == 'Laptop'")
print(laptop_data)

      Customer_ID    Name  Age  Gender       City Product  Price  Quantity  \
0               1  Chetan   39    Male    Chennai  Laptop  45042         3
2               3    Jaya   39  Female  Hyderabad  Laptop  30794         1
3               4    Hari   39    Male  Hyderabad  Laptop  49912         2
7               8    Isha   39  Female  Bangalore  Laptop  49675         5
10             11    Gopi   39  Female  Bangalore  Laptop  12669         3
...           ...     ...  ...     ...        ...     ...    ...       ...
1025          308   Divya   39    Male      Kochi  Laptop  16900         5
1027          404    Bala   39  Female  Bangalore  Laptop  27380         3
1028          741    Jaya   39    Male  Hyderabad  Laptop  48115         4
1033          712  Chetan   39    Male      Kochi  Laptop  14348         4
1040          904   Divya   39  Female  Bangalore  Laptop  35752         1

     Payment_Mode Purchase_Date  Total_amount Age_Group
0             UPI    2023-07-08        135126     36-50
2            Card    2023-07-04         30794     36-50
3            Cash    2023-06-29         99824     36-50
7             UPI    2023-05-25        248375     36-50
10           Cash    2023-08-30         38007     36-50
...           ...           ...           ...       ...
1025         Card    2023-10-28         84500     36-50
1027         Card    2023-04-01         82140     36-50
1028          UPI    2023-05-02        192460     36-50
1033         Cash    2023-09-13         57392     36-50
1040         Card    2023-06-29         35752     36-50

[228 rows x 12 columns]

In [945]:
high_value = df.query("Total_amount > 100000")
print(high_value)

      Customer_ID    Name  Age  Gender        City     Product  Price  \
0               1  Chetan   39    Male     Chennai      Laptop  45042
7               8    Isha   39  Female   Bangalore      Laptop  49675
9              10  Chetan   39    Male   Bangalore      Camera  25442
12             13    Arun   39  Female       Kochi  Headphones  23958
16             17    Jaya   39  Female   Bangalore      Mobile  44114
...           ...     ...  ...     ...         ...         ...    ...
1028          741    Jaya   39    Male   Hyderabad      Laptop  48115
1029          384    Arun   39    Male   Bangalore      Mobile  48035
1037          816    Isha   39    Male   Hyderabad      Camera  39837
1038          343    Hari   39  Female  Trivandrum      Camera  23661
1042          134    Jaya   39    Male   Hyderabad      Tablet  31493

      Quantity Payment_Mode Purchase_Date  Total_amount Age_Group
0            3          UPI    2023-07-08        135126     36-50
7            5          UPI    2023-05-25        248375     36-50
9            4         Card    2023-12-24        101768     36-50
12           5         Cash    2023-04-07        119790     36-50
16           3          UPI    2023-02-20        132342     36-50
...        ...          ...           ...           ...       ...
1028         4          UPI    2023-05-02        192460     36-50
1029         4         Cash    2023-01-11        192140     36-50
1037         3          UPI    2023-12-03        119511     36-50
1038         5         Card    2023-11-27        118305     36-50
1042         4         Card    2023-12-27        125972     36-50

[305 rows x 12 columns]

In [946]:
result = df.query(
    "City == 'Kochi' and  Product == 'Laptop' and Total_amount > 100000"
)
print("Kochi Laptop Transactions above 100000")
print(result)

Kochi Laptop Transactions above 100000
     Customer_ID    Name  Age  Gender   City Product  Price  Quantity  \
35            36  Farhan   39  Female  Kochi  Laptop  38922         4
179          180    Gopi   39    Male  Kochi  Laptop  49073         3
218          219  Chetan   39    Male  Kochi  Laptop  23065         5
309          310  Farhan   39    Male  Kochi  Laptop  40462         5
419          420    Bala   39    Male  Kochi  Laptop  44282         3
500          501    Gopi   39  Female  Kochi  Laptop  44990         3
540          541    Gopi   39    Male  Kochi  Laptop  48954         3
564          565    Arun   39    Male  Kochi  Laptop  26606         4
660          661    Hari   39    Male  Kochi  Laptop  38960         4
844          845  Farhan   39  Female  Kochi  Laptop  33916         4
950          951    Gopi   39    Male  Kochi  Laptop  37248         5
953          954    Hari   39  Female  Kochi  Laptop  47911         3
961          962  Farhan   39    Male  Kochi  Laptop  29592         5

    Payment_Mode Purchase_Date  Total_amount Age_Group
35          Cash    2023-04-21        155688     36-50
179          UPI    2023-03-03        147219     36-50
218         Cash    2023-02-15        115325     36-50
309         Card    2023-06-24        202310     36-50
419         Card    2023-08-31        132846     36-50
500         Card    2023-09-10        134970     36-50
540          UPI    2023-04-05        146862     36-50
564         Cash    2023-11-18        106424     36-50
660         Cash    2023-04-13        155840     36-50
844         Cash    2023-08-14        135664     36-50
950         Card    2023-09-04        186240     36-50
953         Card    2023-11-16        143733     36-50
961         Card    2023-01-23        147960     36-50

In [947]:
sales_by_city = df.groupby("City")["Total_amount"].sum()
print(sales_by_city)

City
Bangalore     15970398
Chennai       15094964
Hyderabad     17038250
Kochi         16114930
Trivandrum    14016286
Name: Total_amount, dtype: int32

In [948]:
avg_product_price = (df.groupby("Product") ["Price"]).mean()
print(avg_product_price)

Product
Camera        23962.138889
Headphones    25815.103139
Laptop        25345.250000
Mobile        25856.227027
Tablet        24042.595960
Name: Price, dtype: float64

In [949]:
quantity_by_product = (
    df.groupby("Product")["Quantity"]).sum()
print(quantity_by_product)

Product
Camera        651
Headphones    655
Laptop        682
Mobile        549
Tablet        576
Name: Quantity, dtype: int64

In [950]:
df.columns

Index(['Customer_ID', 'Name', 'Age', 'Gender', 'City', 'Product', 'Price',
       'Quantity', 'Payment_Mode', 'Purchase_Date', 'Total_amount',
       'Age_Group'],
      dtype='str')

In [951]:
quantity_by_city = (
    df.groupby("City")["Quantity"].sum()
)
print(quantity_by_city)

City
Bangalore     646
Chennai       582
Hyderabad     668
Kochi         625
Trivandrum    592
Name: Quantity, dtype: int64

In [952]:
quantity_by_payment = (
    df.groupby("Payment_Mode")["Quantity"].sum()
    
)
print(quantity_by_payment)

Payment_Mode
Card    1094
Cash    1070
UPI      949
Name: Quantity, dtype: int64

In [953]:
city_analysis = (
    df.groupby("City").agg(
        Total_Sales = ("Total_amount", "sum"),
        Average_Price = ("Price", "mean"),
        Total_Quantity = ("Quantity", "sum")
    )
)

print(city_analysis)

            Total_Sales  Average_Price  Total_Quantity
City
Bangalore      15970398   24651.333333             646
Chennai        15094964   25420.195000             582
Hyderabad      17038250   24961.342342             668
Kochi          16114930   26293.175355             625
Trivandrum     14016286   23667.353234             592

In [954]:
df["Year"] = df["Purchase_Date"].dt.year
df["Month"] = df["Purchase_Date"].dt.month

print(df[["Purchase_Date", "Year", "Month"]])

     Purchase_Date  Year  Month
0       2023-07-08  2023      7
1       2023-12-20  2023     12
2       2023-07-04  2023      7
3       2023-06-29  2023      6
4       2023-10-08  2023     10
...            ...   ...    ...
1045    2023-10-18  2023     10
1046    2023-11-14  2023     11
1047    2023-12-22  2023     12
1048    2023-11-26  2023     11
1049    2023-01-10  2023      1

[1050 rows x 3 columns]

In [955]:
sales_pivot = pd.pivot_table(
    df,
    values="Total_amount",
    index= "City",
    columns= "Product",
    aggfunc="sum"
)
print("Pivot Table for Sales")
print("Sales by city and Product : ")
print(sales_pivot)

Pivot Table for Sales
Sales by city and Product :
Product      Camera  Headphones   Laptop   Mobile   Tablet
City
Bangalore   2974405     2973847  4256571  3609352  2156223
Chennai     3091389     4032873  2431042  2511727  3027933
Hyderabad   3570723     3958871  3783530  2960136  2764990
Kochi       3426891     2826205  3938667  2702103  3221064
Trivandrum  2924334     2695162  2864931  2718223  2813636

In [956]:
quantity_pivot = pd.pivot_table(
    df,
    values="Quantity",
    index="City",
    columns="Product",
    aggfunc="sum"
)

print("\n Pivot table for Quantity")
print("\n Quantity sold by City and Product :")
print(quantity_pivot)

 Pivot table for Quantity

 Quantity sold by City and Product :
Product     Camera  Headphones  Laptop  Mobile  Tablet
City
Bangalore      121         131     179     128      87
Chennai        125         138      95      95     129
Hyderabad      145         163     134     106     120
Kochi          135         111     152     100     127
Trivandrum     125         112     122     120     113

In [957]:
payment_crosstabs = pd.crosstab(
    df["City"],
    df["Payment_Mode"]
)
print("City vs Payment Type :")
print(payment_crosstabs)

City vs Payment Type :
Payment_Mode  Card  Cash  UPI
City
Bangalore       71    70   75
Chennai         79    57   64
Hyderabad       73    84   65
Kochi           81    75   55
Trivandrum      69    71   61

In [958]:
product_gender_crosstab = pd.crosstab(
    df["Product"],
    df["Gender"]
)

print("\n Product vs Gender")
print(product_gender_crosstab)

 Product vs Gender
Gender      Female  Male
Product
Camera         108   108
Headphones     110   113
Laptop         119   109
Mobile         101    84
Tablet         103    95

In [959]:
monthly_sales = (
    df.groupby(["Year", "Month"], as_index=False)["Total_amount"].sum()
)
print( monthly_sales)

    Year  Month  Total_amount
0   2023      1       7049026
1   2023      2       6468086
2   2023      3       7167266
3   2023      4       6137281
4   2023      5       5957046
5   2023      6       6461530
6   2023      7       5876238
7   2023      8       4968311
8   2023      9       7602219
9   2023     10       5382904
10  2023     11       6398981
11  2023     12       8183305
12  2024      1        582635

In [960]:
monthly_sales_pivot = pd.pivot_table(
    df,
    values="Total_amount",
    index="Month",
    columns="Year",
    aggfunc="sum"
)
print("\n Monthly Sales Pivot Table :")
print(monthly_sales_pivot)

 Monthly Sales Pivot Table :
Year        2023      2024
Month
1      7049026.0  582635.0
2      6468086.0       NaN
3      7167266.0       NaN
4      6137281.0       NaN
5      5957046.0       NaN
6      6461530.0       NaN
7      5876238.0       NaN
8      4968311.0       NaN
9      7602219.0       NaN
10     5382904.0       NaN
11     6398981.0       NaN
12     8183305.0       NaN

In [961]:

city_region = pd.DataFrame({
    "City" : [
        "Chennai",
        "Hyderabad",
        "Kochi",
        "Mumbai",
        "Delhi"
    ],
    "Regions" : [
        "South",
        "South",
        "South",
        "West",
        "North"
    ]
})
print("City-Region Mapping :")
print(city_region)
df = pd.merge(
    df,
    city_region,
    on="City",
    how="left"
)
print(df[["Customer_ID", "City", "Regions"]].head(10))

City-Region Mapping :
        City Regions
0    Chennai   South
1  Hyderabad   South
2      Kochi   South
3     Mumbai    West
4      Delhi   North
   Customer_ID        City Regions
0            1     Chennai   South
1            2   Hyderabad   South
2            3   Hyderabad   South
3            4   Hyderabad   South
4            5       Kochi   South
5            6       Kochi   South
6            7  Trivandrum     NaN
7            8   Bangalore     NaN
8            9     Chennai   South
9           10   Bangalore     NaN

In [962]:
print("Pandas:", pd)

Pandas: <module 'pandas' from 'c:\\Users\\Roshni\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py'>

In [963]:
print("df exists:", "df" in globals())

df exists: True

In [964]:
print("\n Merged Data : ")
print(df[["Customer_ID", "City", "Regions"]].head(10))

 Merged Data :
   Customer_ID        City Regions
0            1     Chennai   South
1            2   Hyderabad   South
2            3   Hyderabad   South
3            4   Hyderabad   South
4            5       Kochi   South
5            6       Kochi   South
6            7  Trivandrum     NaN
7            8   Bangalore     NaN
8            9     Chennai   South
9           10   Bangalore     NaN

In [965]:
print("\n Missing Regions :", df["Regions"].isnull().sum())

 Missing Regions : 417

In [966]:
region_sales = (df.groupby("Regions", as_index=False)["Total_amount"].sum())

In [967]:
print("\nMissing Regions:", df["Regions"].isnull().sum())

Missing Regions: 417

In [968]:
region_sales = (
    df.groupby("Regions", as_index=False)["Total_amount"].sum()
)

In [969]:
print("\nTotal Sales by Region:")
print(region_sales)

Total Sales by Region:
  Regions  Total_amount
0   South      48248144

In [970]:
print(df["City"].unique())

<StringArray>
['Chennai', 'Hyderabad', 'Kochi', 'Trivandrum', 'Bangalore']
Length: 5, dtype: str

In [971]:
df.to_csv("final_processed_dataset.csv", index = False)

In [972]:
df.to_excel("final_processed_Dataset.xlsx", index=False)

In [973]:
df.to_json("final_processed_dataset.json",
orient="records",
indent = 4
)

C:\Users\Roshni\AppData\Local\Temp\ipykernel_4060\4096422450.py:1: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json("final_processed_dataset.json",

In [974]:
import os

print("CSV exists:", os.path.exists("final_processed_dataset.csv"))
print("Excel exists:", os.path.exists("final_processed_dataset.xlsx"))
print("JSON exists:", os.path.exists("final_processed_dataset.json"))

CSV exists: True
Excel exists: True
JSON exists: True

In [975]:
df

,Customer_ID,Name,Age,Gender,City,Product,Price,Quantity,Payment_Mode,Purchase_Date,Total_amount,Age_Group,Year,Month,Regions
0,1,Chetan,39,Male,Chennai,Laptop,45042,3,UPI,2023-07-08,135126,36-50,2023,7,South
1,2,Bala,39,Female,Hyderabad,Tablet,16621,5,Cash,2023-12-20,83105,36-50,2023,12,South
2,3,Jaya,39,Female,Hyderabad,Laptop,30794,1,Card,2023-07-04,30794,36-50,2023,7,South
3,4,Hari,39,Male,Hyderabad,Laptop,49912,2,Cash,2023-06-29,99824,36-50,2023,6,South
4,5,Isha,39,Male,Kochi,Tablet,20258,2,Cash,2023-10-08,40516,36-50,2023,10,South
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1045,300,Gopi,39,Male,Chennai,Mobile,14710,3,Card,2023-10-18,44130,36-50,2023,10,South
1046,833,Esha,39,Male,Trivandrum,Mobile,17436,3,UPI,2023-11-14,52308,36-50,2023,11,NaN
1047,176,Arun,39,Male,Kochi,Tablet,19076,5,Card,2023-12-22,95380,36-50,2023,12,South
1048,897,Isha,39,Male,Trivandrum,Headphones,2578,4,Card,2023-11-26,10312,36-50,2023,11,NaN
1049,600,Chetan,39,Male,Trivandrum,Headphones,35903,1,Card,2023-01-10,35903,36-50,2023,1,NaN

In [976]:
city_product_summary = (
    df.groupby(["City", "Product"])
    .agg(
        Total_Sales = ("Total_amount", "sum"),
        Average_Price = ("Price", "mean"),
        Total_quantity = ("Quantity", "sum"),
        Transaction_count = ("Customer_ID","count")
    )
    .reset_index()

)

print(city_product_summary)

          City     Product  Total_Sales  Average_Price  Total_quantity  \
0    Bangalore      Camera      2974405   22958.342105             121
1    Bangalore  Headphones      2973847   24904.413043             131
2    Bangalore      Laptop      4256571   24456.210526             179
3    Bangalore      Mobile      3609352   27078.166667             128
4    Bangalore      Tablet      2156223   23496.393939              87
5      Chennai      Camera      3091389   25708.619048             125
6      Chennai  Headphones      4032873   28734.800000             138
7      Chennai      Laptop      2431042   24992.969697              95
8      Chennai      Mobile      2511727   24367.216216              95
9      Chennai      Tablet      3027933   22903.627907             129
10   Hyderabad      Camera      3570723   23579.367347             145
11   Hyderabad  Headphones      3958871   24211.000000             163
12   Hyderabad      Laptop      3783530   27070.812500             134
13   Hyderabad      Mobile      2960136   27698.468750             106
14   Hyderabad      Tablet      2764990   22988.523810             120
15       Kochi      Camera      3426891   25259.173913             135
16       Kochi  Headphones      2826205   25224.868421             111
17       Kochi      Laptop      3938667   26774.096154             152
18       Kochi      Mobile      2702103   27991.342857             100
19       Kochi      Tablet      3221064   26386.075000             127
20  Trivandrum      Camera      2924334   22105.658537             125
21  Trivandrum  Headphones      2695162   26157.976744             112
22  Trivandrum      Laptop      2864931   22849.815789             122
23  Trivandrum      Mobile      2718223   22525.230769             120
24  Trivandrum      Tablet      2813636   24480.900000             113

    Transaction_count
0                  38
1                  46
2                  57
3                  42
4                  33
5                  42
6                  45
7                  33
8                  37
9                  43
10                 49
11                 51
12                 48
13                 32
14                 42
15                 46
16                 38
17                 52
18                 35
19                 40
20                 41
21                 43
22                 38
23                 39
24                 40

In [977]:
df["Sales_Category"] = df["Total_amount"].apply(
    lambda x: "High" if x > 50000 else "Normal"
)

print(
    df[["Customer_ID", "Total_amount", "Sales_Category"]].head(10)
)

   Customer_ID  Total_amount Sales_Category
0            1        135126           High
1            2         83105           High
2            3         30794         Normal
3            4         99824           High
4            5         40516         Normal
5            6         25157         Normal
6            7         18287         Normal
7            8        248375           High
8            9         16455         Normal
9           10        101768           High

In [978]:
df = df.drop_duplicates()

In [979]:
print("Total records:", len(df))
print("Unique Customer_IDs:", df["Customer_ID"].nunique())

Total records: 1000
Unique Customer_IDs: 1000

In [980]:
print("Customer_IDs are unique:", df["Customer_ID"].is_unique)

Customer_IDs are unique: True

In [981]:
duplicate_ids = df[
    df["Customer_ID"].duplicated(keep=False)
]

print(duplicate_ids[["Customer_ID", "Name", "City", "Product"]])

Empty DataFrame
Columns: [Customer_ID, Name, City, Product]
Index: []

In [982]:
print("Duplicate Customer_ID count:",
      df["Customer_ID"].duplicated().sum())

Duplicate Customer_ID count: 0

In [983]:
print("Total records:", len(df))
print("Unique Customer_IDs:", df["Customer_ID"].nunique())
print("Customer_IDs are unique:", df["Customer_ID"].is_unique)
print("Duplicate Customer_ID count:",
      df["Customer_ID"].duplicated().sum())

Total records: 1000
Unique Customer_IDs: 1000
Customer_IDs are unique: True
Duplicate Customer_ID count: 0