In [2]:
import pandas as pd
data = {
    'Department': ['HR', 'HR', 'IT', 'IT', 'Finance'],
    'Employee': ['A', 'B', 'C', 'D', 'E'],
    'Salary': [3000, 3200, 4000, 4100, 5000]
}
df = pd.DataFrame(data)
pivot = df.pivot_table(values='Salary', index='Department', aggfunc='mean')
print(pivot)

            Salary
Department
Finance     5000.0
HR          3100.0
IT          4050.0

In [3]:
import pandas as pd
data = {
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR']
}
df = pd.DataFrame(data)
ct = pd.crosstab(df['Gender'], df['Department'])
print(ct)

Department  Finance  HR  IT
Gender
Female            0   2   1
Male              1   0   1

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Asha", "Ravi"],
    "Math": [85, 90],
    "Science": [78, 88]
})

result = pd.melt(df, id_vars="Name", var_name="Subject", value_name="Marks")
print(result)

   Name  Subject  Marks
0  Asha     Math     85
1  Ravi     Math     90
2  Asha  Science     78
3  Ravi  Science     88

In [4]:
import pandas as pd

df = pd.DataFrame({
    "Math": [85, 90],
    "Science": [78, 88]
}, index=["Asha", "Ravi"])

result = df.stack()
print(result)

Asha  Math       85
      Science    78
Ravi  Math       90
      Science    88
dtype: int64

In [4]:
import pandas as pd

df = pd.DataFrame({
    "Math": [85, 90],
    "Science": [78, 88]
}, index=["Asha", "Ravi"])

stacked = df.stack()
result = stacked.unstack()
print(result)

      Math  Science
Asha    85       78
Ravi    90       88

In [8]:
import pandas as pd
data = {
    "Name": ["Asha", "Ravi", "Anu", "Rahul"],
    "Age": [23, 25, 24, 26],
    "Department": ["IT", "HR", "IT", "Finance"],
    "Salary": [35000, 30000, 40000, 45000]
}
df = pd.DataFrame(data)
df
df.to_csv("employees.csv", index=False)

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Asha", "Ravi", "Anu", "Rahul"],
    "Age": [23, 25, 24, 26],
    "Department": ["IT", "HR", "IT", "Finance"],
    "Salary": [35000, 30000, 40000, 45000]
})

df

    Name  Age Department  Salary
0   Asha   23         IT   35000
1   Ravi   25         HR   30000
2    Anu   24         IT   40000
3  Rahul   26    Finance   45000

In [2]:
df.to_csv("output.csv", index=False, encoding="utf-8")

In [3]:
import os

print(os.path.exists("output.csv"))

True

In [4]:
print(os.getcwd())

C:\Users\Roshni\Pandas

In [5]:
new_df = pd.read_csv("output.csv")
new_df

    Name  Age Department  Salary
0   Asha   23         IT   35000
1   Ravi   25         HR   30000
2    Anu   24         IT   40000
3  Rahul   26    Finance   45000

In [14]:
import os
import pandas as pd

data = {'City': ['New York', 'Paris'], 'Temperature': [22, 18]}
df = pd.DataFrame(data)

df.to_json('weather.json')

file_path = os.path.abspath('weather.json')
print(f"File saved at: {file_path}")

File saved at: C:\Users\Roshni\Pandas\weather.json

In [12]:
df

       City  Temperature
0  New York           22
1     Paris           18

In [15]:
import os
import pandas as pd

data = {'City': ['New York', 'Paris'], 'Temperature': [22, 18]}
df = pd.DataFrame(data)

df.to_json('weather.json')

file_path = os.path.abspath('weather.json')
print(f"File saved at: {file_path}")

File saved at: C:\Users\Roshni\Pandas\weather.json