In [2]:
import pandas as pd

# Load the Excel file from the location where you saved it
df = pd.read_excel("EXCEL STUFF FOR DATA ANALYTICS\\employees.xlsx")

print(df)

       Name  Age Department  Salary
0      Asha   24         HR   35000
1      Ravi   30         IT   50000
2     Kiran   28         IT   45000
3     Meera   26    Finance   40000
4     Varun   32  Marketing   52000
5     Sneha   27         HR   38000
6     Arjun   29         IT   47000
7     Kavya   25      Sales   36000
8    Manish   31    Finance   53000
9     Priya   23  Marketing   34000
10    Rohit   33      Sales   55000
11    Divya   28         HR   42000
12    Suraj   35         IT   60000
13     Neha   26    Finance   41000
14    Tarun   27      Sales   37000
15  Lakshmi   30  Marketing   48000
16   Naveen   29         IT   46000
17   Harini   24         HR   35500
18    Abdul   34    Finance   58000
19    Pooja   25      Sales   36500

In [5]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\roshni\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\roshni\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

# Load the Excel file from the location where you saved it
df = pd.read_excel("C:\\Users\\Roshni\\OneDrive\\ドキュメント\\EXCEL STUFF FOR DATA ANALYTICS\\employees.xlsx")

print(df)

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Roshni\\OneDrive\\ドキュメント\\EXCEL STUFF FOR DATA ANALYTICS\\employees.xlsx'

In [2]:
import pandas as pd

# Load the Excel file from the location where you saved it
df = pd.read_excel("EXCEL STUFF FOR DATA ANALYTICS/employees.xlsx")

print(df)

       Name  Age Department  Salary
0      Asha   24         HR   35000
1      Ravi   30         IT   50000
2     Kiran   28         IT   45000
3     Meera   26    Finance   40000
4     Varun   32  Marketing   52000
5     Sneha   27         HR   38000
6     Arjun   29         IT   47000
7     Kavya   25      Sales   36000
8    Manish   31    Finance   53000
9     Priya   23  Marketing   34000
10    Rohit   33      Sales   55000
11    Divya   28         HR   42000
12    Suraj   35         IT   60000
13     Neha   26    Finance   41000
14    Tarun   27      Sales   37000
15  Lakshmi   30  Marketing   48000
16   Naveen   29         IT   46000
17   Harini   24         HR   35500
18    Abdul   34    Finance   58000
19    Pooja   25      Sales   36500

In [3]:
import pandas as pd
df = pd.read_csv('EXCEL STUFF FOR DATA ANALYTICS/students.csv')
print(df)

      Name  Age Grade  Subject
0    Alice   20     A     Math
1      Bob   21     B  Science
2  Charlie   22     A  English
3    David   20     C  History
4      Eva   21     B  Physics

In [6]:
df = pd.read_json("EXCEL STUFF FOR DATA ANALYTICS/data.json")
print(df)

      Name  Age Grade  Subject
0    Alice   20     A     Math
1      Bob   21     B  Science
2  Charlie   22     A  English
3    David   20     C  History
4      Eva   21     B  Physics

In [7]:
import sqlite3

conn = sqlite3.connect("company.db")

In [8]:
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS employees (
    id INTEGER PRIMARY KEY,
    name TEXT,
    department TEXT,
    salary INTEGER
)
""")

conn.commit()

In [9]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("company.db")
df = pd.read_sql("SELECT * FROM employees", conn)
print(df)

Empty DataFrame
Columns: [id, name, department, salary]
Index: []

In [13]:
cursor.execute("""
INSERT INTO employees (name, department, salary)
VALUES ('Anu', 'HR', 30000)
""")

cursor.execute("""
INSERT INTO employees (name, department, salary)
VALUES ('Rahul', 'IT', 50000)
""")

cursor.execute("""
INSERT INTO employees (name, department, salary)
VALUES ('Meera', 'Finance', 45000)
""")

conn.commit()

In [11]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("company.db")
df = pd.read_sql("SELECT * FROM employees", conn)
print(df)

Empty DataFrame
Columns: [id, name, department, salary]
Index: []

In [12]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("company.db")
df = pd.read_sql("SELECT * FROM employees", conn)
print(df)

Empty DataFrame
Columns: [id, name, department, salary]
Index: []

In [14]:
cursor = conn.cursor()

cursor.execute("""
INSERT INTO employees (name, department, salary)
VALUES ('Anu', 'HR', 30000)
""")

cursor.execute("""
INSERT INTO employees (name, department, salary)
VALUES ('Rahul', 'IT', 50000)
""")

cursor.execute("""
INSERT INTO employees (name, department, salary)
VALUES ('Meera', 'Finance', 45000)
""")

conn.commit()

OperationalError: database is locked

In [15]:
conn.close()

In [16]:
import sqlite3

conn = sqlite3.connect("company.db")

In [17]:
cursor = conn.cursor()

cursor.execute("""
INSERT INTO employees (name, department, salary)
VALUES ('Anu', 'HR', 30000)
""")

cursor.execute("""
INSERT INTO employees (name, department, salary)
VALUES ('Rahul', 'IT', 50000)
""")

cursor.execute("""
INSERT INTO employees (name, department, salary)
VALUES ('Meera', 'Finance', 45000)
""")

conn.commit()

OperationalError: database is locked

In [18]:
import os

print("Current folder:")
print(os.getcwd())

print("\nDatabase path:")
print(os.path.abspath("company.db"))

print("\nDatabase exists:")
print(os.path.exists("company.db"))

Current folder:
C:\Users\Roshni\Pandas

Database path:
C:\Users\Roshni\Pandas\company.db

Database exists:
True

In [19]:
import sqlite3

conn = sqlite3.connect("company.db", timeout=30)

print("Connected successfully!")

cursor = conn.cursor()

cursor.execute("SELECT * FROM employees")

print(cursor.fetchall())

Connected successfully!
[]

In [ ]:
cursor = conn.cursor()

cursor.execute("""
INSERT INTO employees (name, department, salary)
VALUES ('Anu', 'HR', 30000)
""")

conn.commit()

print("Inserted successfully!")

In [21]:
import sqlite3

conn = sqlite3.connect("company_test.db")
cursor = conn.cursor()

In [22]:
cursor.execute("""
CREATE TABLE employees (
    id INTEGER PRIMARY KEY,
    name TEXT,
    department TEXT,
    salary INTEGER
)
""")

conn.commit()

print("Table created!")

Table created!

In [23]:
cursor.execute("""
INSERT INTO employees (name, department, salary)
VALUES ('Anu', 'HR', 30000)
""")

conn.commit()

print("Inserted successfully!")

Inserted successfully!

In [24]:
import pandas as pd

df = pd.read_sql("SELECT * FROM employees", conn)

df

   id name department  salary
0   1  Anu         HR   30000

In [25]:
import pandas as pd

df = pd.read_sql("SELECT * FROM employees", conn)

print(df)

   id name department  salary
0   1  Anu         HR   30000

In [26]:
import pandas as pd

df = pd.read_csv(
    "students.txt",
    sep="|",
    header=None,
    names=["ID", "Name", "Score"]
)

df

FileNotFoundError: [Errno 2] No such file or directory: 'students.txt'

In [27]:
data = """1|Anu|85
2|Rahul|90
3|Meera|78"""

with open("students.txt", "w") as file:
    file.write(data)

In [28]:
import pandas as pd

df = pd.read_csv(
    "students.txt",
    sep="|",
    header=None,
    names=["ID", "Name", "Score"]
)

df

   ID   Name  Score
0   1    Anu     85
1   2  Rahul     90
2   3  Meera     78

In [29]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
        'Age': [24, 27, 22, 32, 29, 25],
        'Marks': [85, 90, 78, 88, 92, 75]}
df = pd.DataFrame(data)
df.head()

      Name  Age  Marks
0    Alice   24     85
1      Bob   27     90
2  Charlie   22     78
3    David   32     88
4      Eva   29     92

In [30]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
        'Age': [24, 27, 22, 32, 29, 25],
        'Marks': [85, 90, 78, 88, 92, 75]}
df = pd.DataFrame(data)
df.tail()

      Name  Age  Marks
1      Bob   27     90
2  Charlie   22     78
3    David   32     88
4      Eva   29     92
5    Frank   25     75

In [31]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
        'Age': [24, 27, 22, 32, 29, 25],
        'Marks': [85, 90, 78, 88, 92, 75]}
df = pd.DataFrame(data)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      str
 1   Age     6 non-null      int64
 2   Marks   6 non-null      int64
dtypes: int64(2), str(1)
memory usage: 276.0 bytes

In [33]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
        'Age': [24, 27, 22, 32, 29, 25],
        'Marks': [85, 90, 78, 88, 92, 75]}
df = pd.DataFrame(data)
df.describe()

             Age      Marks
count   6.000000   6.000000
mean   26.500000  84.666667
std     3.619392   6.801961
min    22.000000  75.000000
25%    24.250000  79.750000
50%    26.000000  86.500000
75%    28.500000  89.500000
max    32.000000  92.000000

In [35]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
        'Age': [24, 27, 22, 32, 29, 25],
        'Marks': [85, 90, 78, 88, 92, 75]}
df = pd.DataFrame(data)
df.shape

(6, 3)

In [36]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
        'Age': [24, 27, 22, 32, 29, 25],
        'Marks': [85, 90, 78, 88, 92, 75]}
df = pd.DataFrame(data)
df.columns

Index(['Name', 'Age', 'Marks'], dtype='str')

In [37]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
        'Age': [24, 27, 22, 32, 29, 25],
        'Marks': [85, 90, 78, 88, 92, 75]}
df = pd.DataFrame(data)
df.dtypes

Name       str
Age      int64
Marks    int64
dtype: object

In [40]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Asha", "Ravi", "Kiran", "Meera", "Vikram"],
    "Age": [24, 30, 28, 26, 32],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Department": ["HR", "IT", "IT", "Finance", "HR"]
})

df["Gender"] = df["Gender"].astype("category")


df.dtypes

Name               str
Age              int64
Gender        category
Department         str
dtype: object

In [41]:
df

     Name  Age  Gender Department
0    Asha   24  Female         HR
1    Ravi   30    Male         IT
2   Kiran   28    Male         IT
3   Meera   26  Female    Finance
4  Vikram   32    Male         HR

In [42]:
import pandas as pd

data = {"Name": ["Asha", "Ravi", "Kiran"]}
df = pd.DataFrame(data, index=["row1", "row2", "row3"])
df

       Name
row1   Asha
row2   Ravi
row3  Kiran

In [45]:
import pandas as pd

arrays = [
    ["India", "India", "USA", "USA"],
    ["2023", "2024", "2023", "2024"]
]

index = pd.MultiIndex.from_arrays(arrays, names=("Country", "Year"))

df = pd.DataFrame({"Sales": [100, 120, 90, 110]}, index=index)

df

              Sales
Country Year
India   2023    100
        2024    120
USA     2023     90
        2024    110

In [3]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
        'Age': [24, 27, None, 32, 29, 25],
        'Marks': [85, 90, 78, 88, 92, 75]}
df = pd.DataFrame(data)
print(df.isnull())
print(df.isnull().sum())

    Name    Age  Marks
0  False  False  False
1  False  False  False
2  False   True  False
3  False  False  False
4  False  False  False
5  False  False  False
Name     0
Age      1
Marks    0
dtype: int64

In [4]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
        'Age': [24, 27, 22, 32, 29, 25],
        'Marks': [85, 90, 78, 88, 92, 75]}
df = pd.DataFrame(data)
df.dtypes

Name       str
Age      int64
Marks    int64
dtype: object

In [7]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [24, 25, 23], 'Marks': [85, 90, 78]}
df = pd.DataFrame(data)
print(df['Name'])
print(df[['Name', 'Marks']])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str
      Name  Marks
0    Alice     85
1      Bob     90
2  Charlie     78

In [3]:

df[['Name', 'Marks']

SyntaxError: incomplete input (3406050970.py, line 1)

In [14]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [24, 25, 23], 'Marks': [85, 90, 78]}
df = pd.DataFrame(data)
print(df.loc[0])
print(df.loc[0, 'Marks'])
print(df.loc[:, ['Name', 'Marks']])

Name     Alice
Age         24
Marks       85
Name: 0, dtype: object
85
      Name  Marks
0    Alice     85
1      Bob     90
2  Charlie     78

In [17]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [24, 25, 23], 'Marks': [85, 90, 78]}
df = pd.DataFrame(data)
print(df.iloc[1])
print(df.iloc[1, 2])
print(df.iloc[:, [0, 2]])

Name     Bob
Age       25
Marks     90
Name: 1, dtype: object
90
      Name  Marks
0    Alice     85
1      Bob     90
2  Charlie     78

In [18]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [24, 25, 23], 'Marks': [85, 90, 78]}
df = pd.DataFrame(data)
print(df.loc[0:1, ['Name', 'Marks']])

    Name  Marks
0  Alice     85
1    Bob     90

In [19]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [24, 25, 23], 'Marks': [85, 90, 78]}
df = pd.DataFrame(data)
print(df.iloc[0:2])

    Name  Age  Marks
0  Alice   24     85
1    Bob   25     90

In [20]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [24, 25, 23], 'Marks': [85, 90, 78]}
df = pd.DataFrame(data)
print(df[df['Marks'] >= 85])

    Name  Age  Marks
0  Alice   24     85
1    Bob   25     90

In [21]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Asha", "Ravi", "Kiran", "Meera"],
    "Age": [24, 30, 28, 26],
    "Dept": ["HR", "IT", "IT", "Finance"]
})

result = df[(df["Age"] > 25) & (df["Dept"] == "IT")]
print(result)

    Name  Age Dept
1   Ravi   30   IT
2  Kiran   28   IT

In [22]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Asha", "Ravi", "Kiran", "Meera"],
    "Age": [24, 30, 28, 26],
    "Dept": ["HR", "IT", "IT", "Finance"]
})

result = df.query("Age > 25 and Dept == 'IT'")
print(result)

    Name  Age Dept
1   Ravi   30   IT
2  Kiran   28   IT

In [23]:
import pandas as pd
df = pd.DataFrame({
    "Sales": [100, 200, 150]
})
df["Discounted_Sales"] = df["Sales"] * 0.9
print(df)

   Sales  Discounted_Sales
0    100              90.0
1    200             180.0
2    150             135.0

In [24]:
import pandas as pd
df = pd.DataFrame({
    "Status": ["pending", "pending", "completed"]
})
df.loc[df["Status"] == "pending", "Status"] = "in progress"
print(df)

        Status
0  in progress
1  in progress
2    completed

In [26]:
import pandas as pd
df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6],
    "C": [7, 8, 9]
})
df = df.drop(columns=["B"])
df

   A  C
0  1  7
1  2  8
2  3  9

In [31]:
import pandas as pd
df = pd.DataFrame({
    "A": [1, 2],
    "B": [3, 4]
})
df = df.map(lambda x: x * 10)
df

    A   B
0  10  30
1  20  40

In [32]:
import pandas as pd
df = pd.DataFrame({
    "Age": [22, 35, 40],
    "City": ["Delhi", "Mumbai", "Delhi"]
})
filtered = df[(df["Age"] > 30) & (df["City"] == "Delhi")]
filtered

   Age   City
2   40  Delhi

In [33]:
import pandas as pd
df = pd.DataFrame({
    "City": ["New York", "New Delhi", "Yorkshire"]
})
filtered = df[df["City"].str.contains("York")]
filtered

        City
0   New York
2  Yorkshire

In [34]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Marks': [85, None, 78]}
df = pd.DataFrame(data)
df_filled = df.fillna(0)
df_filled

      Name  Marks
0    Alice   85.0
1      Bob    0.0
2  Charlie   78.0

In [35]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Marks': [85, None, 78]}
df = pd.DataFrame(data)
df_dropped = df.dropna()
df_dropped

      Name  Marks
0    Alice   85.0
2  Charlie   78.0

In [37]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Grade': ['A', 'B', 'F']}
df = pd.DataFrame(data)
df_replaced = df.replace({'F': 'Fail'})
df_replaced

      Name Grade
0    Alice     A
1      Bob     B
2  Charlie  Fail

In [38]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Asha", "Ravi", "Asha", "Kiran"],
    "Age": [24, 30, 24, 28]
})

df.duplicated()

0    False
1    False
2     True
3    False
dtype: bool

In [52]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Alice"],
    "Marks": [85, 90, 85]
})

print(df)

    Name  Marks
0  Alice     85
1    Bob     90
2  Alice     85

In [53]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Alice"],
    "Marks": [85, 90, 85]
})

print(df)
print(df.drop_duplicates())

    Name  Marks
0  Alice     85
1    Bob     90
2  Alice     85
    Name  Marks
0  Alice     85
1    Bob     90

In [54]:
import pandas as pd

df = pd.DataFrame({
    "City": ["mumbai", "Delhi", "chennai", "Kolkata"]
})

df["City_Upper"] = df["City"].str.upper()
print(df)

      City City_Upper
0   mumbai     MUMBAI
1    Delhi      DELHI
2  chennai    CHENNAI
3  Kolkata    KOLKATA

In [55]:
import pandas as pd

df = pd.DataFrame({
    "Product": ["Apple Juice", "Mango Shake", "Orange Juice", "Banana Smoothie"]
})

mask = df["Product"].str.contains("Juice")
result = df[mask]
print(result)

        Product
0   Apple Juice
2  Orange Juice

In [56]:
import pandas as pd
data = {'Name': ['Alice', 'Bob'], 'Marks': [85, 90]}
df = pd.DataFrame(data)
df_renamed = df.rename(columns={'Marks': 'Score'})
print(df_renamed)

    Name  Score
0  Alice     85
1    Bob     90

In [59]:
import pandas as pd
data = {'Name': ['Alice', 'Bob'], 'Marks': [85, 90]}
df = pd.DataFrame(data)

df['Marks'] = df['Marks'].astype(str)


print(df.dtypes)

Name     str
Marks    str
dtype: object

In [60]:
import pandas as pd
data = {'Name': ['Alice', 'Bob'], 'Marks': [85, 90]}
df = pd.DataFrame(data)
sorted_df = df.sort_values(by='Marks', ascending=False)
print(sorted_df)

    Name  Marks
1    Bob     90
0  Alice     85

In [61]:
import pandas as pd
data = {'Name': ['Alice', 'Bob'], 'Marks': [85, 90]}
df = pd.DataFrame(data)
df = df.sort_index()
print(df)

    Name  Marks
0  Alice     85
1    Bob     90

In [62]:
import pandas as pd
data = {'Name': ['Alice', 'Bob'], 'Marks': [85, 90]}
df = pd.DataFrame(data)
df = df.sort_index()
print(df)

    Name  Marks
0  Alice     85
1    Bob     90

In [2]:
import pandas as pd
data = {'Name': ['Alice', 'Bob'], 'Marks': [85, 90]}
df = pd.DataFrame(data)
df_indexed = df.set_index('Name')
print(df_indexed)

       Marks
Name
Alice     85
Bob       90

In [4]:
import pandas as pd
data = {'Name': ['Alice', 'Bob'], 'Marks': [85, 90]}
df = pd.DataFrame(data)
df_indexed = df.set_index('Name')
print(df_indexed)
df_reset = df_indexed.reset_index(drop=True)
print(df_reset)

       Marks
Name
Alice     85
Bob       90
   Marks
0     85
1     90

In [5]:
import pandas as pd
data = {'Math': [85, 90, 78], 'Science': [92, 88, 95]}
df = pd.DataFrame(data)
print(df.sum())
print(df.mean())
print(df.count())
print(df.min())
print(df.max())

Math       253
Science    275
dtype: int64
Math       84.333333
Science    91.666667
dtype: float64
Math       3
Science    3
dtype: int64
Math       78
Science    88
dtype: int64
Math       90
Science    95
dtype: int64

In [7]:
import pandas as pd
df = pd.DataFrame({
    "Math": [80, 90, 85],
    "Science": [75, 88, 92]
})
result = df.apply(sum, axis=1)
print(result)

0    155
1    178
2    177
dtype: int64

In [8]:
import pandas as pd
df = pd.DataFrame({
    "Marks": [45, 72, 88]
})
df["Result"] = df["Marks"].apply(lambda x: "Pass" if x >= 50 else "Fail")
print(df)

   Marks Result
0     45   Fail
1     72   Pass
2     88   Pass

In [9]:
import pandas as pd
df = pd.DataFrame({
    "Math": [80, 90],
    "Science": [70, 85]
})
df["Total"] = df.apply(lambda row: row["Math"] + row["Science"], axis=1)
print(df)

   Math  Science  Total
0    80       70    150
1    90       85    175

In [12]:
import pandas as pd
names = pd.Series(['alice', 'bob', 'charlie', 'roshni'])
capitalized = names.map(str.title)
print(capitalized)

0      Alice
1        Bob
2    Charlie
3     Roshni
dtype: str

In [13]:
import pandas as pd
grades = pd.Series(["A", "B", "C", "A"])
grade_points = {"A": 5, "B": 4, "C": 3}
points = grades.map(grade_points)
print(points)

0    5
1    4
2    3
3    5
dtype: int64

In [14]:
import pandas as pd
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "HR"],
    "Salary": [50000, 40000, 55000, 42000]
})
df["Dept_Avg_Salary"] = df.groupby("Department")["Salary"].transform("mean")
print(df)

  Department  Salary  Dept_Avg_Salary
0         IT   50000          52500.0
1         HR   40000          41000.0
2         IT   55000          52500.0
3         HR   42000          41000.0

In [15]:
import pandas as pd
data = {'Math': [85, 90, 78], 'Science': [92, 88, 95]}
df = pd.DataFrame(data)
df['Total'] = df['Math'] + df['Science']
print(df)

   Math  Science  Total
0    85       92    177
1    90       88    178
2    78       95    173

In [16]:
import pandas as pd
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'ID': [1, 2, 4], 'Score': [85, 90, 88]})
merged = pd.merge(df1, df2, on='ID', how='inner')
print(merged)

   ID   Name  Score
0   1  Alice     85
1   2    Bob     90

In [22]:
import pandas as pd
df1 = pd.DataFrame({'A': ['A0', 'A1'], 'B': ['B0', 'B1']})
df2 = pd.DataFrame({'A': ['A2', 'A3'], 'B': ['B2', 'B3']})
result = pd.concat([df1, df2], axis=1, ignore_index=True)
print(result)

    0   1   2   3
0  A0  B0  A2  B2
1  A1  B1  A3  B3

In [23]:
import pandas as pd
df1 = pd.DataFrame({'Name': ['Alice', 'Bob']}, index=[1, 2])
df2 = pd.DataFrame({'Score': [85, 90]}, index=[1, 2])
joined = df1.join(df2)
print(joined)

    Name  Score
1  Alice     85
2    Bob     90

In [24]:
import pandas as pd
df1 = pd.DataFrame({'Name': ['Alice', 'Bob']}, index=[1, 2])
df2 = pd.DataFrame({'Score': [85, 90]}, index=[1, 2])
joined = df1.join(df2, how='inner')
print(joined)

    Name  Score
1  Alice     85
2    Bob     90

In [26]:
df1 = pd.DataFrame(
    {'Name': ['Alice', 'Bob', 'Charlie']},
    index=[1, 2, 3]
)

df2 = pd.DataFrame(
    {'Score': [85, 90, 88]},
    index=[1, 2, 4]
)
df1.join(df2)

      Name  Score
1    Alice   85.0
2      Bob   90.0
3  Charlie    NaN

In [27]:
df1 = pd.DataFrame(
    {'Name': ['Alice', 'Bob', 'Charlie']},
    index=[1, 2, 3]
)

df2 = pd.DataFrame(
    {'Score': [85, 90, 88]},
    index=[1, 2, 4]
)
df1.join(df2, how='inner')

    Name  Score
1  Alice     85
2    Bob     90

In [28]:
df1 = pd.DataFrame(
    {'Name': ['Alice', 'Bob', 'Charlie']},
    index=[1, 2, 3]
)

df2 = pd.DataFrame(
    {'Score': [85, 90, 88]},
    index=[1, 2, 4]
)


df1.join(df2, how='right')

    Name  Score
1  Alice     85
2    Bob     90
4    NaN     88

In [29]:
import pandas as pd
data = {'Department': ['HR', 'HR', 'IT', 'IT', 'Finance'],
        'Salary': [40000, 45000, 60000, 62000, 50000]}
df = pd.DataFrame(data)

grouped = df.groupby('Department')
print(grouped['Salary'].mean())

Department
Finance    50000.0
HR         42500.0
IT         61000.0
Name: Salary, dtype: float64

In [32]:
import pandas as pd
data = {
    'Team': ['A', 'A', 'B', 'B', 'A'],
    'Gender': ['M', 'F', 'M', 'F', 'M'],
    'Score': [88, 92, 85, 90, 75]
}
df = pd.DataFrame(data)

# Group by one column
print(df.groupby('Team')['Score'].mean())

# Group by multiple columns
df.groupby(['Team', 'Gender'])['Score'].mean()

Team
A    85.0
B    87.5
Name: Score, dtype: float64

Team  Gender
A     F         92.0
      M         81.5
B     F         90.0
      M         85.0
Name: Score, dtype: float64

In [33]:
import pandas as pd
data = {
    'Team': ['A', 'A', 'B', 'B', 'A'],
    'Gender': ['M', 'F', 'M', 'F', 'M'],
    'Score': [88, 92, 85, 90, 75]
}
df = pd.DataFrame(data)

def range_func(series):
    return series.max() - series.min()

grouped = df.groupby('Team')['Score'].agg(range_func)
print(grouped)

Team
A    17
B     5
Name: Score, dtype: int64

In [2]:
import pandas as pd
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "HR"],
    "Salary": [50000, 40000, 55000, 42000]
})
result = df.groupby("Department").agg({
    "Salary": ["sum", "mean"]
})
print(result)

            Salary
               sum     mean
Department
HR           82000  41000.0
IT          105000  52500.0

In [3]:
import pandas as pd
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "HR"],
    "Salary": [50000, 40000, 55000, 42000]
})
result = df.groupby("Department").agg(
    Total_Salary=("Salary", "sum"),
    Average_Salary=("Salary", "mean")
)
print(result)

            Total_Salary  Average_Salary
Department
HR                 82000         41000.0
IT                105000         52500.0

In [4]:
import pandas as pd
data = {
    'Department': ['HR', 'HR', 'IT', 'IT', 'Finance'],
    'Employee': ['A', 'B', 'C', 'D', 'E'],
    'Salary': [3000, 3200, 4000, 4100, 5000]
}
df = pd.DataFrame(data)
pivot = df.pivot_table(values='Salary', index='Department', aggfunc='mean')
print(pivot)

            Salary
Department
Finance     5000.0
HR          3100.0
IT          4050.0